apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kubernetes
  labels:
    app: my-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-kubernetes"
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        eks.tke.cloud.tencent.com/cpu-type: amd
        eks.tke.cloud.tencent.com/security-group-id: sg-56mfwq82
      labels:
        app: "my-kubernetes"
    spec:
      containers:
      - name: apiserver
        image: ccr.ccs.tencentyun.com/leiwang/hyperkube:v1.18.6-rancher1
        imagePullPolicy: Always
        args: 
        - kube-apiserver
        - --allow-privileged=true
        - --apiserver-count=3
        - --audit-log-maxage=30
        - --audit-log-maxbackup=3
        - --audit-log-maxsize=100
        - --audit-log-path=/var/log/audit.log
        - --authorization-mode=Node,RBAC
        - --bind-address=0.0.0.0
        - --secure-port=443
        - --insecure-bind-address=0.0.0.0
        - --insecure-port=80
        - --client-ca-file=/var/lib/kubernetes/ca.pem
        - --enable-admission-plugins=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
        - --enable-swagger-ui=true
        - --etcd-servers=http://172.17.16.44:2379
        - --event-ttl=1h
        - --kubelet-certificate-authority=/var/lib/kubernetes/ca.pem 
        - --requestheader-client-ca-file=/var/lib/kubernetes/ca.pem 
        - --kubelet-client-certificate=/var/lib/kubernetes/kubernetes.pem 
        - --kubelet-client-key=/var/lib/kubernetes/kubernetes-key.pem 
        - --kubelet-https=true 
        - --service-account-key-file=/var/lib/kubernetes/service-account.pem 
        - --service-cluster-ip-range=10.32.0.0/24 
        - --service-node-port-range=30000-32767 
        - --tls-cert-file=/var/lib/kubernetes/kubernetes.pem 
        - --tls-private-key-file=/var/lib/kubernetes/kubernetes-key.pem 
        - --proxy-client-cert-file=/var/lib/kubernetes/kubernetes.pem 
        - --proxy-client-key-file=/var/lib/kubernetes/kubernetes-key.pem
        - --v=2
        resources:
          requests:
            memory: 250Mi
            cpu: 250m
          limits:
            memory: 250Mi
            cpu: 250m
        volumeMounts:
          - name: config
            mountPath: /var/lib/kubernetes
      volumes:
        - name: config
          configMap:
            name: config