apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    app: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "controller-manager"
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        eks.tke.cloud.tencent.com/cpu-type: amd
        eks.tke.cloud.tencent.com/security-group-id: sg-56mfwq82
      labels:
        app: "controller-manager"
    spec:
      containers:
      - name: controller-manager
        image: ccr.ccs.tencentyun.com/leiwang/hyperkube:v1.18.6-rancher1
        imagePullPolicy: Always
        args: 
        - kube-controller-manager
        - --address=0.0.0.0 
        - --cluster-cidr=10.200.0.0/16 
        - --cluster-name=kubernetes 
        - --cluster-signing-cert-file=/var/lib/kubernetes/ca.pem 
        - --cluster-signing-key-file=/var/lib/kubernetes/ca-key.pem 
        - --authentication-kubeconfig=/var/lib/kubernetes/kube-controller-manager.kubeconfig
        - --authorization-kubeconfig=/var/lib/kubernetes/kube-controller-manager.kubeconfig
        - --kubeconfig=/var/lib/kubernetes/kube-controller-manager.kubeconfig 
        - --leader-elect=true 
        - --root-ca-file=/var/lib/kubernetes/ca.pem 
        - --service-account-private-key-file=/var/lib/kubernetes/service-account-key.pem 
        - --service-cluster-ip-range=10.32.0.0/24 
        - --use-service-account-credentials=true 
        - --client-ca-file=/var/lib/kubernetes/ca.pem
        - --requestheader-client-ca-file=/var/lib/kubernetes/ca.pem
        - --v=2
        resources:
          requests:
            memory: 250Mi
            cpu: 250m
          limits:
            memory: 250Mi
            cpu: 250m
        volumeMounts:
          - name: config
            mountPath: /var/lib/kubernetes
      volumes:
        - name: config
          configMap:
            name: config