---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtual-kubelet
  labels:
    k8s-app: virtual-kubelet
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: virtual-kubelet
subjects:
  - kind: ServiceAccount
    name: virtual-kubelet
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-kubelet
  labels:
    k8s-app: kubelet
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      k8s-app: virtual-kubelet
  template:
    metadata:
      labels:
        pod-type: virtual-kubelet
        k8s-app: virtual-kubelet
    spec:
      containers:
        - name: virtual-kubelet
          image: ccr.ccs.tencentyun.com/leiwang/virtual-node:v0.1-7-g79ac0394c93acf
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBELET_PORT
              value: "10450"
            - name: APISERVER_CERT_LOCATION
              value: /etc/kubernetes/virtual-kubelet.pem
            - name: APISERVER_KEY_LOCATION
              value: /etc/kubernetes/virtual-kubelet-key.pem
            - name: DEFAULT_NODE_NAME
              value: virtual-kubelet
            - name: VKUBELET_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - --provider=k8s 
            - --client-kubeconfig="a" 
            - --kubeconfig=/etc/kubernetes/admin.kubeconfig
            - --nodename=virtual-kubelet 
            - --disable-taint=true 
            - --kube-api-qps=1 
            - --kube-api-burst=1 
            - --client-qps=5 
            - --client-burst=1 
            - --klog.v=3 
            - --log-level=debug 
            - --metrics-addr=:10455 
          resources:
            requests:
              memory: 250Mi
              cpu: 150m
            limits:
              memory: 250Mi
              cpu: 150m
          livenessProbe:
            tcpSocket:
              port: 10450
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
          - name: config
            mountPath: /etc/kubernetes
      volumes:
        - name: config
          configMap:
            name: config
      serviceAccountName: virtual-kubelet